apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: emptydir-container  
    image: alpine 
    command: ['sh','-c','sleep 3000']
    volumeMounts:
    - mountPath: /mnt/demo
      name: test-volume
  volumes:
  - name: test-volume
    emptyDir: {}


apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - mountPath: /mnt/vol
      name: myvolume
  volumes:
  - name: myvolume
    emptyDir: {}
